// <auto-generated />
using BookMVC.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookMvc.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230612172328_AddedImageUrlToProduct")]
    partial class AddedImageUrlToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookMvc.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 0,
                            Name = "Cartoon"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 1,
                            Name = "Novel"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 2,
                            Name = "SciFi"
                        });
                });

            modelBuilder.Entity("BookMvc.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Golwyn Mayor",
                            CategoryId = 1,
                            ImageUrl = "",
                            Price100 = 75.0,
                            Price50 = 85.0,
                            Title = "Tom & Jerry",
                            UnitPrice = 100.0
                        },
                        new
                        {
                            Id = 2,
                            Author = "20th Century Fox",
                            CategoryId = 3,
                            ImageUrl = "",
                            Price100 = 95.0,
                            Price50 = 110.0,
                            Title = "Passengers",
                            UnitPrice = 125.0
                        },
                        new
                        {
                            Id = 3,
                            Author = "Unknown",
                            CategoryId = 2,
                            ImageUrl = "",
                            Price100 = 98.0,
                            Price50 = 110.0,
                            Title = "Game Of Thrones",
                            UnitPrice = 150.0
                        });
                });

            modelBuilder.Entity("BookMvc.Models.Product", b =>
                {
                    b.HasOne("BookMvc.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
